---
title: "Bibliography Setup"
author:
  name: "Thomas Roppelt"
  affiliation: "Friedrich-Alexander-Universität Erlangen-Nürnberg (FAU)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
bibliography: library.bib
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Bibliography Managers
Bibliography managers are important to keep all the literature you work with well organized.
This page will help you understand pros and cons of different bibliography managers as well as help you set up Zotero, a free and open-source bibliography manager.

## Comparison
There are many different bibliography managers available, e.g. Citavi, Colwiz, EndNote, JabRef, Mendeley, Zotero and ZoteroBib.
Since we focus on open-source software, software like Citavi and EndNote are out of question.
Of the named software, only JabRef, Zotero and ZoteroBib are free and open source.
For a detailed feature comparison, you may want to look [here (german)](https://ub.fau.de/schreiben-publizieren/literaturverwaltung/) or [here (english)](https://en.wikipedia.org/wiki/Comparison_of_reference_management_software).
While the following paragraphs will cover Zotero, please feel free to use any of the other open source bibliography managers. As long as they can handle the [BibTex format](https://de.wikipedia.org/wiki/BibTeX) it should be all fine.

## Zotero setup
To get started with Zotero, there are some components that should be set up:
- install Zotero itself
  - via chocolatey package manager (recommended)
    Run in bash or command line: `choco install zotero`
  - download and install via the [Zotero website](https://www.zotero.org/)
- the BetterBibTex Addon for Zotero. [installation instructions](https://retorque.re/zotero-better-bibtex/installation/)
    - Among other things, this enables an automatic export of the bib file.
    - Prerequisite: Zotero.
- the Zotero-picker Addon for Atom. [installation instructions](https://atom.io/packages/zotero-picker)
    - It enables you to quote and cite directly in Atom.
    - Prerequisites: Zotero, BetterBibTex Addon
- (optional, but recommended) a Zotero connector for your browser [installation instructions](https://www.zotero.org/download/connectors)
    - This enables you to add the websites or PDFs you view in your browser directly to your bibliography. And as much as possible will be automatically tagged.
    - Prerequisite: Zotero

## Using Zotero
This should be pretty straightforward. To learn about the available functions, have a look at the [Zotero Quick Start Guide](https://www.zotero.org/support/quick_start_guide)

## Finalizing a document
Navigate with command prompt / bash to the folder your .md document (and in this example, also the .bib file) is stored. The following command will generate a new file in HTML format:
pandoc .\homework.md --bibliography=mybib.bib -o .\Outputs\output.html
- `-o` defines the output location to be a subfolder of the current location.
- The default format is HTML, so this is what will be generated.

## Linux distributions (distros)
Looking at Linux distributions and deciding for one can be a daunting task if this is new to you.
Keep in mind that while there are notable differences between distros, making an informed choice is very difficult. So just taking a distro and trying it out (it's free!) might be the better choice.
Anyway, here are some resources to help you with the first steps.
- [DistroWatch](http://distrowatch.org/). This page has all the distros and sorts them by popularity. You will find key information about the distros and userratings here.
- [A beginner's guide article by PCWorld](https://www.pcworld.com/article/2918397/how-to-get-started-with-linux-a-beginners-guide.html)
- And many more, just use your favourite search engine.
