---
title: "Bibliography Setup"
author:
  name: "Thomas Roppelt"
  affiliation: "Friedrich-Alexander-Universität Erlangen-Nürnberg (FAU)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
bibliography: library.bib
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Bibliography Managers
Bibliography managers are important to keep all the literature you work with well organized.
This page will help you understand pros and cons of different bibliography managers as well as help you set up Zotero, a free and open-source bibliography manager.

## Comparison
There are many different bibliography managers available, e.g. Citavi, Colwiz, EndNote, JabRef, Mendeley, Zotero and ZoteroBib.
Since we focus on open-source software, software like Citavi and EndNote are out of question.
Of the named software, only JabRef, Zotero and ZoteroBib are free and open source.
For a detailed feature comparison, you may want to look [here (german)](https://ub.fau.de/schreiben-publizieren/literaturverwaltung/) or [here (english)](https://en.wikipedia.org/wiki/Comparison_of_reference_management_software).
While the following paragraphs will cover Zotero, please feel free to use any of the other open source bibliography managers. As long as they can handle the [BibTex format](https://de.wikipedia.org/wiki/BibTeX) it should be all fine.

## Zotero setup
To get started with Zotero, there are some components that should be set up:
- install Zotero itself
  - via chocolatey package manager (recommended)
    Run in bash or command line: `choco install zotero`
  - download and install via the [Zotero website](https://www.zotero.org/)
- the BetterBibTex Addon for Zotero. [installation instructions](https://retorque.re/zotero-better-bibtex/installation/)
    - Among other things, this enables an automatic export of the bib file.
    - Prerequisite: Zotero.
- the Zotero-picker Addon for Atom. [installation instructions](https://atom.io/packages/zotero-picker)
    - It enables you to quote and cite directly in Atom.
    - Prerequisites: Zotero, BetterBibTex Addon
- (optional, but recommended) a Zotero connector for your browser [installation instructions](https://www.zotero.org/download/connectors)
    - This enables you to add the websites or PDFs you view in your browser directly to your bibliography. And as much as possible will be automatically tagged.
    - Prerequisite: Zotero

## Using Zotero
This should be pretty straightforward. To learn about the available functions, have a look at the [Zotero Quick Start Guide](https://www.zotero.org/support/quick_start_guide)

## Finalizing a document
Navigate with command prompt / bash to the folder your .md document (and in this example, also the .bib file) is stored. The following command will generate a new file in HTML format:
pandoc .\homework.md --bibliography=mybib.bib -o .\Outputs\output.html
- `-o` defines the output location to be a subfolder of the current location.
- The default format is HTML, so this is what will be generated.

## Linux distributions (distros)
Looking at Linux distributions and deciding for one can be a daunting task if this is new to you.
Keep in mind that while there are notable differences between distros, making an informed choice is very difficult. So just taking a distro and trying it out (it's free!) might be the better choice.
Here are some key differences between distributions:
- _Release Model_
The release model decides how frequently updates reach your system. Frequent smaller updates are called rolling release. If only very big updates are released, it is a point or major release model. 
Also, distros can either focus on well-tested and known software, while others focus on the bleeding edge.
- _Basis and forks_
This is where a lot of names are being dropped, e.g. Arch, Debian, RedHat. While it is not important to remember every name in the beginning, it is important to understand the concept. 
If a distribution derives from another distribution, it is called a fork (similar to the git concept). The basis of a distribution defines e.g. which system tools you have available and thereby also which software packages you can install in general. 
[See this image](https://upload.wikimedia.org/wikipedia/commons/1/1b/Linux_Distribution_Timeline.svg) to make out which distro forked from where.
Example:
Manjaro Linux is based on Arch Linux. Therefore, it is a fork of Arch. And while it has its own software repository, due to being derived from Arch it can also install software packages from the Arch User Repository. However, it is not related to Ubuntu, a fork of Debian. So it is basically not possible to install Debian packages in Manjaro. Keep in mind there are almost always ways to work around such limitations.
- _Design principles_
Each distro has its own principles. Some try to be as beginner-friendly as possible (e.g. Ubuntu) and take a lot of choices from the user, while others encourage users to really learn the system (e.g. Arch). Pick a distro and read a little about it to find one that you believe suits your needs.

Summing it up, there are quite substantial differences between the linux distributions. Since it is impossible to understand every linux distro in the necessary detail to make an informed decision, think about what you really need and then just get started

Here are some resources to help you with the first steps.
- [DistroWatch](http://distrowatch.org/). This page has all the distros and sorts them by popularity. You will find key information about the distros and useful user ratings here.
- [A linux beginner's guide article by PCWorld](https://www.pcworld.com/article/2918397/how-to-get-started-with-linux-a-beginners-guide.html)
- [Overview about the best linux distros 2019](https://linoxide.com/linux-how-to/what-are-best-linux-distros/)
- And many more, just use your favourite search engine.


The following tools were tested on Manjaro (fork of Arch Linux), but might also work on other distros.
- Backup
Backups are essential. No matter if it was caused by an update or misconfiguration by the user, having a backup can save a lot of hassle. 
  - Software: *Timeshift*, [Link to GitHub Project](https://github.com/teejee2008/timeshift)
  - Functionality: Timeshift makes it easy to create and restore backups. By default it saves the system configuration, but it can also be configured to backup configuration and all your files. 
  - Comment: Put the Timeshift backups on an external medium, e.g. a USB-drive. In case something goes horribly wrong, the backups won't be affected. Also, having a "rescue system" ready can be helpful to restore these backups. A rescue system can be e.g. a USB-Drive or even a disk with a bootable linux distribution on it. Most distros have instructions how to create a bootable medium on their website.


